name: CI

on:
  push:
    branches:
      - main  # ou la branche que vous utilisez

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Remplacez "3.x" par la version de Python que vous utilisez


    - name: Install dependencies
      run: |
        cd $GITHUB_WORKSPACE
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: testing secrets
      run: echo "${{ secrets.DOCKER_USERNAME }}"

    - name: Print sys.path
      run: python -c "import sys; print(sys.path)"

    - name: Install mongodb
      uses: supercharge/mongodb-github-action@1.6.0

    - name: Create logs folder
      run: mkdir -p $GITHUB_WORKSPACE/logs

    - name: Change to the repository root
      run: cd $GITHUB_WORKSPACE

    - name: Run tests
      run: |
        pytest ./tests/conftest.py

    - name: Run linter (exemple avec flake8)
      run: |
        pip install flake8
        flake8 .

  publish: 
    runs-on: ubuntu-latest

    needs : testing
    if : success()

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Dockerhub login
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PW }}
      
    - name: metadata extraction
      id: meta
      uses: docker/metadata-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        images: Insiares/Scraper
      
    - name: Build and push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file : ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}