name: CI

on:
  push:
    branches:
      - main  # ou la branche que vous utilisez

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Remplacez "3.x" par la version de Python que vous utilisez

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Si vous avez un fichier requirements.txt

    - name: Install mongodb
      run: |
        sudo apt-get install mongodb

    - name: run mongodb
      run: |
        sudo service mongodb start

    - name: Change to the repository root
      run: cd $GITHUB_WORKSPACE

    - name: Run tests
      run: |
        python -m pytest ./tests/conftest.py

    - name: Run linter (exemple avec flake8)
      run: |
        pip install flake8
        flake8 .