name: CI

on:
  push:
    branches:
      - main  # ou la branche que vous utilisez

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Remplacez "3.x" par la version de Python que vous utilisez


    - name: Install dependencies
      run: |
        cd $GITHUB_WORKSPACE
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Print sys.path
      run: python -c "import sys; print(sys.path)"

    - name: Install mongodb
      uses: supercharge/mongodb-github-action@1.6.0

    - name: Create logs folder
      run: mkdir -p $GITHUB_WORKSPACE/logs

    - name: Change to the repository root
      run: cd $GITHUB_WORKSPACE

    - name: Start Flask server in background
      run: |
        python app.py &  
        sleep 10  # Wait for the server to start (adjust as needed)

    - name: Run tests
      run: |
        python -m pytest ./tests/conftest.py

    - name: Stop Flask server
      run: pkill -f 'python app.py'

    - name: Run linter (exemple avec flake8)
      run: |
        pip install flake8
        flake8 .
